language: cpp
sudo: required
dist: trusty
compiler:
  - gcc
before_install:
  - sudo apt-get -qq update
install:
  - sudo apt-get -qq install autoconf automake autotools-dev libtool pkg-config
  - sudo apt-get -qq install libssl-dev ruby
before_script:
  - echo '-------------------------------'
  - echo 'Resolve dependencies           '
  - echo '-------------------------------'
  - git clone --depth 1 https://github.com/mruby/mruby.git
  - git clone --depth 1 https://github.com/facebook/rocksdb.git
  - cd rocksdb/
  - make shared_lib
  - sudo cp ./librocksdb.* /usr/lib/
  - sudo cp -r ./include/rocksdb/ /usr/include/
  - cd ../
script:
  - echo '-------------------------------'
  - echo 'Run unit test                  '
  - echo '-------------------------------'
  - mkdir -p mruby/build/host/mrbgems/
  - cd mruby/ && MRUBY_CONFIG=../travis_config.rb ./minirake test && cd ../
